version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: erp_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-erp_database}
      POSTGRES_USER: ${DB_USER:-erp_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-erp_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - erp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-erp_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: erp_redis_dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - erp_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ERP API with Hot Reload
  api:
    image: golang:1.23-alpine
    container_name: erp_api_dev
    restart: unless-stopped
    working_dir: /app
    ports:
      - "${API_PORT:-8081}:8081"
    environment:
      - APP_ENV=${APP_ENV:-development}
      - CONFIG_PATH=/app/data/config.yml
      - CGO_ENABLED=0
    volumes:
      - .:/app
      - go_modules:/go/pkg/mod
    networks:
      - erp_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        apk add --no-cache git make &&
        go install github.com/cosmtrek/air@v1.49.0 &&
        air -c .air.toml
      "

  # PgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: erp_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@erp.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    networks:
      - erp_network
    depends_on:
      - postgres

networks:
  erp_network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local
  go_modules:
    driver: local
